name = "web-programming-project"
type = "javascript"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2026-01-06"

[site]
bucket = "./public"
entry-point = "workers-site"
